site_name: Presidential Speeches
theme_dir: theme
theme: null
copyright: 'Copyright &copy; 2018 <a href="mailto:kellyteel@mail.usf.edu">Kelly Teel</a>'
repo_url: https://github.com/KellyTeel/presidental-speeches
repo_name: 'GitHub'
pages:
- Home: 'index.md'
- Background: 'background.md'
- Source Analysis: 'source_analysis.md'
- Workflow: 'workflow.md'
- Initial Findings: 'initial_findings.md'
- Reflections: 'reflections.md'
- Bibliography and Credits: 'biblio_and_credits.md'
